# Generated by Django 5.2 on 2025-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='player_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='server_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
